version: '3'

services:
    nodejsapp:
        build:
          context: ./app
        container_name: nodejsapp
        hostname: nodejsapp
        ports:
            - "3000:8080" 
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "8080:80" 
