version: '3'

services:
    nodejs-app:
        build:
          context: ./app
        container_name: nodejsserver
        hostname: localhost
        ports:
            - "3000:8888" 
        networks:
            - example-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
    external: true